### ISSUE TITLE
Chrome app already existing on Macbook breaks gu-base

### ISSUE THREAD

**Issue by katebee** [guardian/homebrew-devtools#22]
## When does the issue occur

Setting up a new Macbook and running `brew cask install guardian/devtools/gu-base`

## What happens

Homebrew errors and exits early due to Chrome already existing as part of the dev build:
 
```
Error: It seems there is already an App at '/Applications/Google Chrome.app'.
```

Since Chrome is one of the first applications to install, this means Homebrew does not get to the good stuff, such as IntelliJ or iTerm2 😢

**Comment by philmcmahon** [comment]
I've 'fixed' this by removing chrome from the cask 😄
