### ISSUE TITLE
adoptopenjdk8 fails in gu-base.rb

### ISSUE THREAD

**Issue by buck06191** [guardian/homebrew-devtools#42]
Update 61056fd to gu-base.rb fails when using `strap.sh`. 
Error message:
```All Formula dependencies satisfied.
Error: Cask 'adoptopenjdk8' is unavailable: No Cask with this name exists.
!!! Executing 'brew cask install gu-base': FAILED
```
Can be fixed manually by running `brew cask install adoptopenjdk/openjdk/adoptopenjdk8` prior to running`strap.sh`

**Comment by buck06191** [comment]
README.md for adoptopenjdk homebew suggests that changing to just adoptopenjdk may be the best general solution. [See README.md here](https://github.com/AdoptOpenJDK/homebrew-openjdk)

**Comment by philmcmahon** [comment]
Thanks @buck06191 - I followed your suggestion and tried the script on my machine with some success, hopefully this is now resolved

**Comment by buck06191** [comment]
Hi Phil,
The change in commit 5ee90b appears to have had some unintended side effects - it installs AdoptOpenJDK13 and this looks to be incompatible with some libraries. Particularly, when building Ophan I found that the Twitter Scrooge library throws errors that are potentially due to incompatibilities later than version 11.
